# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Configuration version (required):
version: 2

# Build from the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Optionally build docs in additional formats as well as default HTML:
formats:
  - pdf

python:
  version: 3
