# This is a special configuration file to run tests on Travis-CI via
# GitHub notifications when changes are committed.
#
# This file is not intended for end users of the tool.

# We don't need sudo so can avoid slower legacy TravisCI infrastructure
sudo: false

language: python
python: "3.6"
cache: pip

before_install:
 - "if grep -P '\t' *.md */*.md */*/*.md; then echo 'Tabs are bad, please use four spaces in Markdown files.'; false; fi"
 - "if grep -P '\t' *.yml .circleci/*.yml ; then echo 'Tabs are bad, please use four spaces in Yaml files.'; false; fi"
 - "if grep -P '\t' */*.py ; then echo 'Tabs are bad, please use four spaces in Python files.'; false; fi"
 - "if grep -n -r '[[:blank:]]$' *.md */*.md */*/*.md; then echo 'Please remove trailing whitespace in Markdown files.'; false; fi"
 - "if grep -n -r '[[:blank:]]$' *.yml .circleci/*.yml ; then echo 'Please remove trailing whitespace in Yaml files.'; false; fi"
 - "if grep -n -r '[[:blank:]]$' */*.py; then echo 'Please remove trailing whitespace in Python files.'; false; fi"

install:
 - pip install --upgrade pip setuptools
 - pip install flake8 flake8-blind-except flake8-docstrings flake8-rst-docstrings restructuredtext-lint
 - pip install -r requirements.txt
 - python -c "import Bio; print(Bio.__version__)"
 - python -c "import sqlalchemy; print(sqlalchemy.__version__)"

script:
 - echo "Using flake8 to check Python code"
 - flake8 .
