# This is a special configuration file to run tests on Circle-CI via
# GitHub notifications when changes are committed.
#
# This file is not intended for end users of the tool.

version: 2
jobs:
  build:
    docker:
      - image: continuumio/miniconda3
    steps:
      - checkout
      - run:
          name: Setup Conda
          command: |
            conda config --set always_yes yes --set changeps1 no
            conda update -q conda
            # In future point at project-env.yml file here:
            conda create -q -n myenv python=3.7
            source activate myenv
            python --version
            conda info -a
      - run:
          name: Whitespace checks
          command: |
            if grep -P '\t' *.md */*.md */*/*.md; then echo 'Tabs are bad, please use four spaces in Markdown files.'; false; fi
            if grep -P '\t' *.yml .circleci/*.yml ; then echo 'Tabs are bad, please use four spaces in Yaml files.'; false; fi
            if grep -P '\t' */*.py; then echo 'Tabs are bad, please use four spaces in Python files.'; false; fi
            if grep -n -r '[[:blank:]]$' *.md */*.md */*/*.md; then echo 'Please remove trailing whitespace in Markdown files.'; false; fi
            if grep -n -r '[[:blank:]]$' *.yml .circleci/*.yml ; then echo 'Please remove trailing whitespace in Yaml files.'; false; fi
            if grep -n -r '[[:blank:]]$' */*.py; then echo 'Please remove trailing whitespace in Python files.'; false; fi
      - run:
          name: Flake8 Python checks
          command: |
            pip install --upgrade pip setuptools
            pip install flake8 flake8-blind-except flake8-docstrings flake8-rst-docstrings restructuredtext-lint
            flake8 .
      - run:
          name: Installation
          command: |
            conda install --file requirements.txt
            pip install .
      - run:
          name: Test
          command: |
            python -c "import thapbi_pict; print(thapbi_pict.__version__)"
            thapbi_pict -v
            python -m thapbi_pict -v
            # thapbi_pict legacy-import 2>&1 | grep "the following arguments are required"
            thapbi_pict legacy-import -d "sqlite:///tests/legacy-import/dup_seqs.sqlite" tests/legacy-import/dup_seqs.fasta
            if [ `sqlite3 tests/legacy-import/dup_seqs.sqlite "SELECT COUNT(id) FROM data_source;"` == "1" ]; then true; else echo "Wrong count"; false; fi
            if [ `sqlite3 tests/legacy-import/dup_seqs.sqlite "SELECT COUNT(id) FROM its1_source;"` == "8" ]; then true; else echo "Wrong count"; false; fi
            if [ `sqlite3 tests/legacy-import/dup_seqs.sqlite "SELECT COUNT(id) FROM its1_sequence;"` == "2" ]; then true; else echo "Wrong count"; false; fi
            thapbi_pict legacy-import -d "sqlite:///database/legacy/database.sqlite" database/legacy/database.fasta
            thapbi_pict legacy-import -d "sqlite:///:memory:" database/legacy/Phytophthora_ITS_database_v0.004.fasta
            thapbi_pict legacy-import -d "database/legacy/Phytophthora_ITS_database_v0.005.sqlite" database/legacy/Phytophthora_ITS_database_v0.005.fasta
            # thapbi_pict dump 2>&1 | grep "the following arguments are required"
            thapbi_pict dump -d "sqlite:///database/legacy/Phytophthora_ITS_database_v0.005.sqlite" -o /dev/null
            thapbi_pict dump -d "sqlite:///database/legacy/Phytophthora_ITS_database_v0.005.sqlite" -o /dev/null -c 8a,8b
            thapbi_pict dump -d "database/legacy/database.sqlite" -o /dev/null -c -
            thapbi_pict legacy-import -d $TMP/legacy_004_and_005.sqlite database/legacy/Phytophthora_ITS_database_v0.004.fasta -n "Legacy DB v0.004"
            thapbi_pict legacy-import -d $TMP/legacy_004_and_005.sqlite database/legacy/Phytophthora_ITS_database_v0.005.fasta -n "Legacy DB v0.005"
            if [ `sqlite3 $TMP/legacy_004_and_005.sqlite "SELECT COUNT(id) FROM data_source;"` == "2" ]; then true; else echo "Wrong count"; false; fi
            if [ `sqlite3 $TMP/legacy_004_and_005.sqlite "SELECT COUNT(id) FROM its1_source;"` == "378" ]; then true; else echo "Wrong count"; false; fi
            if [ `sqlite3 $TMP/legacy_004_and_005.sqlite "SELECT COUNT(id) FROM its1_sequence;"` == "172" ]; then true; else echo "Wrong count"; false; fi